# Generated by Django 5.0.7 on 2024-10-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=300)),
                ('email', models.EmailField(default='', max_length=255)),
                ('phone_number', models.CharField(default=0, max_length=20)),
                ('amount', models.PositiveBigIntegerField(default=0)),
                ('ref', models.CharField(max_length=200)),
                ('verified', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
