# Generated by Django 5.0.7 on 2024-10-16 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='article',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
