# Generated by Django 5.0.7 on 2024-11-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_blog_content1_blog_content10_blog_content11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='godey', unique=True),
        ),
    ]
