# Generated by Django 5.0.7 on 2024-12-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0005_smslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
