# Generated by Django 4.1 on 2022-12-09 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0006_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
