# Generated by Django 4.1 on 2022-12-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0008_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
