# Generated by Django 4.1 on 2022-12-10 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0010_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
