# Generated by Django 4.1 on 2022-12-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0011_delete_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='portfolio-img')),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField()),
            ],
        ),
    ]
