# Generated by Django 4.1 on 2023-06-22 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0014_portfolio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
