# Generated by Django 4.1 on 2023-06-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0017_alter_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='link',
        ),
    ]
