# Generated by Django 5.0.7 on 2024-10-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0017_alter_contact_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='Youtube',
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-title']},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='link',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='content',
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
