# Generated by Django 4.1 on 2023-06-22 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0018_article_remove_blog_author_remove_blog_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
