# Generated by Django 4.1 on 2023-06-23 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0020_article_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Youtube',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='content',
        ),
    ]
