# Generated by Django 4.1 on 2023-06-23 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0021_delete_youtube_remove_portfolio_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
