# Generated by Django 4.1 on 2023-06-23 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0022_delete_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
