# Generated by Django 5.0.7 on 2024-10-02 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0025_alter_portfolio_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
