# Generated by Django 5.0.7 on 2024-10-11 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0026_remove_blog_article_remove_blog_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
