# Generated by Django 5.0.7 on 2024-10-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0026_remove_blog_article_remove_blog_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content1',
            field=models.TextField(blank=True, default='', max_length=250, null=True),
        ),
    ]
