# Generated by Django 5.0.7 on 2024-10-11 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0027_alter_blog_content1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
