# Generated by Django 5.0.7 on 2024-10-11 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0029_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
