# Generated by Django 5.0.7 on 2024-10-11 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0028_alter_blog_content1_alter_blog_content10_and_more'),
        ('my_site', '0031_blog'),
    ]

    operations = [
    ]
