# Generated by Django 5.0.7 on 2024-10-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0032_merge_20241011_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
